FROM nvidia/cuda:11.0.3-base-ubuntu20.04


RUN apt-get update && apt install --no-install-recommends -y build-essential \
    python3-pip \
    git \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/* \
    && git clone https://github.com/lavallone/wsd_sota.git && cd wsd_sota \
    && chmod +x setup.sh && ./setup.sh \
    && wget https://huggingface.co/lavallone/escher/resolve/main/escher_semcor_best.ckpt -O esc/experiments/escher_semcor_best.ckpt

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda3.sh \
    && chmod +x Miniconda3.sh \
    && ./Miniconda3.sh -b -p /opt/conda \
    && rm Miniconda3.sh

ENV PATH="/opt/conda/bin:$PATH"
RUN conda init bash && echo "conda activate esc" >> ~/.bashrc

RUN conda create -n esc python=3.7 -y \
    && /bin/bash -c "source activate esc \
    && cd /wsd_sota/esc \
    && pip install --no-cache-dir -r requirements.txt"

RUN pip install nltk && \
    python -c "import nltk; nltk.download('wordnet', quiet=True)"

WORKDIR /wsd_sota/esc
