FROM nvidia/cuda:11.0.3-base-ubuntu20.04


RUN apt-get update && apt install --no-install-recommends -y build-essential \
    python3-pip \
    git \
    wget \
    unzip \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && git clone https://github.com/lavallone/wsd_sota.git && cd wsd_sota \
    && chmod +x setup.sh && ./setup.sh \
    && wget https://huggingface.co/lavallone/consec/resolve/main/consec_semcor_normal_best.ckpt?download=true -O consec/experiments/released-ckpts/consec_semcor_normal_best.ckpt \
    && wget https://huggingface.co/lavallone/consec/resolve/main/pairs_counter.txt?download=true -O consec/data/pmi/pairs_counter.txt

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda3.sh \
    && chmod +x Miniconda3.sh \
    && ./Miniconda3.sh -b -p /opt/conda \
    && rm Miniconda3.sh

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/opt/conda/bin:$PATH"
RUN conda init bash && echo "conda activate consec" >> ~/.bashrc

RUN conda create -n consec python=3.7 -y && \
    /bin/bash -c "source /opt/conda/bin/activate consec && \
    cd /wsd_sota/consec && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    source $HOME/.cargo/env && \
    pip install --no-cache-dir -r requirements.txt"

RUN pip install nltk && \
    python -c "import nltk; nltk.download('wordnet', quiet=True)"

WORKDIR /wsd_sota/consec

